language: csharp
solution: phaxio-dotnet.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - mono .nuget/nuget.exe restore phaxio-dotnet.sln
  - mono .nuget/nuget.exe install NUnit.Runners -Version 3.2.1 -OutputDirectory tools
script:
  - xbuild /p:Configuration=Release phaxio-dotnet.sln /p:TargetFrameworkVersion="v4.5"
  - mono ./tools/NUnit.Runners.2.6.3/tools/nunit-console.exe ./Phaxio.Tests/bin/Release/Phaxio.Tests.dll